name: Java CI

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [main]
    types:
      - opened
      - reopened
      - synchronize
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build:
    name: Build with Java 21
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 21

    # # check ant version
    - name: Ant Version
      run: ant -version

    # - name: Ant Build (target jars)
    #   run: ant -noinput -buildfile build.xml jars

    # - name: Ant Build (target dtdjars)
    #   run: ant -noinput -buildfile build.xml dtdjars

    # - name: Ant Test (target ci-test)
    #   run: ant -noinput -buildfile build.xml clean ci-test

    # - name: Ant Build (target all)
    #   run: ant -noinput -buildfile build.xml all

    # # clean up before running via build script
    # - name: Ant Clean
    #   run: ant -noinput -buildfile build.xml clean

    # The README suggests to use a build script to call ant
    # so we do this as well to make sure it also works this way
    - name: Run build script (target jars)
      run: . ./build.sh jars

    - name: LS test
      run: ls -a

    # - name: Run build script (target dtdjars)
    #   run: . ./build.sh dtdjars

    # # clean up before running via build script
    # # TODO might want to make the clean step a part of build.sh
    # - name: Ant Clean
    #   run: ant -noinput -buildfile build.xml clean

    # - name: Run build script (target test)
    #   run: . ./build.sh test

    # # clean up before running via build script
    # - name: Ant Clean
    #   run: ant -noinput -buildfile build.xml clean

    # - name: Run build script (target all)
    #   run: . ./build.sh all
